name: 'ArgoCD'
description: 'GitHub Action for ArgoCD'
inputs:
  version:
    description: 'Version'
    required: true
    default: '1.2.2'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
